# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  # substitutions can be changed here if you are using this file directly in the ESPHome dashboard.  The better approach is
  # to incorporate this file as a package using the following lines, and then overwrite these substitutions in your local
  # yaml file by redefining them.
  #
  # packages:
  #   kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb-lite.yaml
  #

  name: kauf-bulb              # **** CHANGE DEVICE NAME TO SOMETHING UNIQUE PER DEVICE.  RENAME YAML FILE TO SAME NAME.    ****
                               # **** USE DASHES (-) INSTEAD OF SPACES OR UNDERSCORE (_).  USE ONLY LOWER CASE LETTERS.     ****

  friendly_name: Kauf Bulb     # **** CHANGE FRIENDLY NAME TO SOMETHING UNIQUE PER DEVICE ****

  disable_entities: "true"     # set to "false" to have all entities show up in Home Assistant automatically

  # https://esphome.io/components/light/index.html#base-light-configuration
  light_restore_mode: RESTORE_INVERTED_DEFAULT_OFF  # change power-on action for main light entity
  default_power_on_state: "Restore Power Off State"

  wifi_ap_timeout: 2min    # default to 2 minute timeout for yaml file as package.

  # https://esphome.io/components/esphome.html#esphome-creators-project
  project_name: Kauf.RGBWW
  project_ver_num: "1.913"
  project_ver_let: l

  sub_on_turn_on:  script_do_nothing
  sub_on_turn_off: script_do_nothing

  sub_red_pin:    GPIO4
  sub_green_pin:  GPIO12
  sub_blue_pin:   GPIO14
  sub_cw_pin:     GPIO5
  sub_ww_pin:     GPIO13

  sub_warm_white_temp: 350 mireds
  sub_cold_white_temp: 150 mireds

  sub_red_freq:   200 hz
  sub_green_freq: 200 hz
  sub_blue_freq:  200 hz
  sub_cw_freq:    400 hz
  sub_ww_freq:    400 hz


# https://esphome.io/components/esp8266.html
esp8266:
  board: esp01_1m
  restore_from_flash: true


# https://esphome.io/guides/automations.html#global-variables
globals:
  - id: global_quick_boot_count
    type: int
    restore_value: yes
    initial_value: '0'


# https://esphome.io/components/esphome.html
esphome:

  name: $name

  project:
    name: $project_name
    version: $project_ver_num($project_ver_let)

  on_boot:
    then:
      - script.execute: script_quick_boot


# https://esphome.io/components/button/index.html
# https://esphome.io/components/button/restart.html
button:
  - platform: restart
    id: restart_button
    name: $friendly_name Restart Firmware
    entity_category: diagnostic
    disabled_by_default: $disable_entities


# https://esphome.io/components/wifi.html
wifi:

  ssid: initial_ap
  password: asdfasdfasdfasdf

  # default is 20, 17 is recommended.
  output_power: 17

  # using fast_connect as default since it is required for hidden networks.
  fast_connect: true

  ap:
    ap_timeout: $wifi_ap_timeout


# https://esphome.io/components/captive_portal.html
captive_portal:


# https://esphome.io/components/logger.html
logger:


# https://esphome.io/components/api.html
api:
  id: kauf_api


# https://esphome.io/components/ota.html
ota:
  on_error:
    then:
      - button.press: restart_button


# https://esphome.io/components/web_server.html
web_server:
  local: true


# PWM outputs for each LED channel
# https://esphome.io/components/output/esp8266_pwm.html
output:
  - platform: esp8266_pwm
    pin: $sub_red_pin
    frequency: $sub_red_freq
    id: pwm_red
    max_power: .8
  - platform: esp8266_pwm
    pin: $sub_green_pin
    frequency: $sub_green_freq
    id: pwm_green
    max_power: .8
  - platform: esp8266_pwm
    pin: $sub_blue_pin
    frequency: $sub_blue_freq
    id: pwm_blue
    max_power: .8
  - platform: esp8266_pwm
    pin: $sub_cw_pin
    frequency: $sub_cw_freq
    id: pwm_cw
    max_power: .8
  - platform: esp8266_pwm
    pin: $sub_ww_pin
    frequency: $sub_ww_freq
    id: pwm_ww
    max_power: .8


# https://esphome.io/components/light/index.html
light:
  - platform: rgbww
    name: $friendly_name
    id: kauf_light
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    warm_white: pwm_ww
    cold_white: pwm_cw
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    restore_mode: RESTORE_DEFAULT_ON


# https://esphome.io/components/select/index.html
# https://esphome.io/components/select/template.html
select:

  # default light state on boot
  - platform: template
    name: $friendly_name Power On State
    id: select_boot_state
    optimistic: true
    options:
      - "Restore Power Off State"
      - "Always On - Last Value"
      - "Always On - Bright White"
      - "Always Off"
      - "YAML Configured ($light_restore_mode)"
    # defaulting to always on is nice so you know new bulbs are working
    initial_option: $default_power_on_state
    restore_value: true
    icon: mdi:restart-alert
    on_value:
      - lambda: |-
          if ( x == "Restore Power Off State")
            kauf_light->set_restore_mode(LIGHT_RESTORE_DEFAULT_OFF);
          else if ( x == "Always On - Last Value")
            kauf_light->set_restore_mode(LIGHT_RESTORE_AND_ON);
          else if ( x == "Always On - Bright White")
            kauf_light->set_restore_mode(LIGHT_ALWAYS_ON);
          else if ( x == "Always Off")
            kauf_light->set_restore_mode(LIGHT_RESTORE_AND_OFF);
          else
            kauf_light->set_restore_mode(LIGHT_$light_restore_mode);
      - script.execute: script_save_changes
    entity_category: config


# https://esphome.io/components/number/index.html
# https://esphome.io/components/number/template.html
number:      # set max power output for PWMs
  - platform: template
    name: ${friendly_name} Max Power
    min_value: 1
    max_value: 100
    step: 1
    initial_value: 80
    id: number_max_power
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:brightness-percent
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: box
    on_value:
      - lambda: |-
          float new_power = ((float)x)/100.0f;
          id(pwm_red).set_max_power(new_power);
          id(pwm_green).set_max_power(new_power);
          id(pwm_blue).set_max_power(new_power);
          id(pwm_ww).set_max_power(new_power);
          id(pwm_cw).set_max_power(new_power);
      - script.execute: script_save_changes

  - platform: template
    name: ${friendly_name} Default Fade
    min_value: 0
    max_value: 5000
    step: 50
    initial_value: 250
    id: number_default_fade
    entity_category: config
    icon: mdi:timer-outline
    optimistic: true
    restore_value: true
    unit_of_measurement: "ms"
    mode: box
    on_value:
      - lambda: id(kauf_light)->set_default_transition_length(x);
      - script.execute: script_save_changes


# https://esphome.io/components/switch/index.html
# https://esphome.io/components/switch/template.html
switch:
  - platform: template
    id: switch_no_hass
    name: $friendly_name No HASS
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:toggle-switch-off-outline
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - lambda: id(kauf_api)->set_reboot_timeout(0);
      - script.execute: script_save_changes
    on_turn_off:
      - lambda: id(kauf_api)->set_reboot_timeout(900000);
      - script.execute: script_save_changes


# https://esphome.io/components/sensor/uptime.html
sensor:
  - platform: uptime
    name: $friendly_name Uptime
    update_interval: 60s
    entity_category: diagnostic
    disabled_by_default: $disable_entities


# Send IP Address to HA.
# https://esphome.io/components/text_sensor/wifi_info.html
text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
      entity_category: diagnostic
      disabled_by_default: $disable_entities


# https://esphome.io/guides/automations.html#script-component
script:
  - id: script_save_changes
    mode: restart
    then:
      - delay: 3s
      - lambda: global_preferences->sync();

  - id: script_do_nothing
    then:
      lambda: return;

    # increment global_quick_boot_count if bulb stays on less than 10 seconds or never connects to wifi
    # reset wifi credentials if the counter gets to 15
  - id: script_quick_boot
    then:

      # if quick boot count is 15, overwrite wifi credentials to force AP
      - if:
          condition:
            lambda: return ( id(global_quick_boot_count) >= 15 );
          then:

            - lambda: |-
                ESP_LOGD("kauf-bulb.yaml", "quick boot count variable is now 15, overwriting credentials and rebooting");

                // overwrite wifi credentials
                wifi::global_wifi_component->save_wifi_sta("initial_ap","asdfasdfasdfasdf");

                // reset counter and immediately save
                id(global_quick_boot_count) = 0;
                global_quick_boot_count->loop();
                global_preferences->sync();

                // turn on red light
                auto call = id(kauf_light).turn_on();
                call.set_transition_length(500);
                call.set_brightness(0.6);
                call.set_rgb(1.0, 0.0, 0.0); // color in RGB order, this example is purple
                call.perform();

              # short delay
            - delay: 5s

              # reboot
            - button.press: restart_button


      # increment quick boot counter so it will stay incremented if device reboots
      - lambda: |-
          ESP_LOGD("kauf-bulb.yaml", "quick boot count variable is now %d.  Need 15 to overwrite credentials", id(global_quick_boot_count));
          id(global_quick_boot_count) += 1;
          global_quick_boot_count->loop();
          global_preferences->sync();

      # if quick boot count gets over 1 (don't flash on first occurrence in case it's an accident), flash light to indicate we are in process
      - if:
          condition:
            lambda: return ( id(global_quick_boot_count) > 2 );
          then:
            - light.turn_on:
                id: kauf_light
                brightness: 50%
                red:   100%
                green: 100%
                blue:    0%
                transition_length: 1s
            - delay: 2s
            - light.turn_off: kauf_light

      # wait 10 seconds
      - delay: 10s
      - lambda: ESP_LOGD("kauf-bulb.yaml", "quick boot script, 10 seconds up");

      # wait until wifi is connected
      - wait_until: wifi.connected
      - lambda: ESP_LOGD("kauf-bulb.yaml", "quick boot script, wifi connected");

      # any time boot is greater than 10 seconds and also connects to wifi, reset quick boot count to 0
      - lambda: |-
          id(global_quick_boot_count) = 0;
          global_quick_boot_count->loop();
          global_preferences->sync();

