substitutions:
  project_ver_let: u
  sub_update_source: http://kaufha.com/kauf-manifests/bulb/manifest.json
  sub_update_release_url: https://github.com/KaufHA/kauf-rgbww-bulbs/releases/latest
  sub_update_firmware_url: https://github.com/KaufHA/kauf-rgbww-bulbs/releases/latest/download/kauf-bulb-v{version}-update-1m.bin.gz


packages:
  kauf_bulb_plus: !include kauf-bulb-plus.yaml


dashboard_import:
  package_import_url: $sub_import_url


esphome:
  name_add_mac_suffix: true


wifi:
  # add forced hash which isn't needed for dashboard import.
  # Allows saving wifi credentials across update.
  forced_hash: 2048874009


# embed the web server's js file for binary update files
web_server:
  local: true


http_request:
  esp8266_disable_ssl_support: true


update:
  - platform: kauf_esp8266_update
    name: Firmware Update
    source: $sub_update_source
    release_url: $sub_update_release_url
    firmware_url: $sub_update_firmware_url
    update_interval: 7d
