substitutions:
  project_ver_let: u


packages:
  kauf_bulb_plus: !include kauf-bulb-plus.yaml


dashboard_import:
  package_import_url: $sub_import_url


esphome:
  name_add_mac_suffix: true


wifi:
  # add forced hash which isn't needed for dashboard import.
  # Allows saving wifi credentials across update.
  forced_hash: 2048874009


# embed the web server's js file for binary update files
web_server:
  local: true
